In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame ({
    'SEX' : ['M', 'F', 'F', 'D', '?'],
    'Age' : [29, 30, 24, 290, 25]
})
df

  SEX  Age
0   M   29
1   F   30
2   F   24
3   D  290
4   ?   25

## finding unique values

In [4]:
# the first step to clean invalid values is to notice them, then identify them and finally 
#handle them appropriately(remove them, replace them) etc.in our dataframe
#we have 'sex' column which only takes in values like 'M' and 'F' but we have a 'D' and '?'
#we are gonna use the .unique() method
df['SEX'].unique()

array(['M', 'F', 'D', '?'], dtype=object)

In [5]:
# or we can use .value_counts()
df['SEX'].value_counts()

SEX
F    2
M    1
D    1
?    1
Name: count, dtype: int64

In [6]:
#clearly if you see values like 'D' or '?' are not appropriate identifiers in "SEX"
#let's say you have been told that 'D' was a typo and it should be replace with 'F'
#for that we use the .replace() function
df['SEX'].replace('D', 'F')

0    M
1    F
2    F
3    F
4    ?
Name: SEX, dtype: object

In [8]:
df[df['Age'] > 100]

  SEX  Age
3   D  290

In [10]:
df.loc[df['Age'] > 100, 'Age'] = df.loc[df['Age'] > 100, 'Age'] / 100
df

  SEX   Age
0   M  29.0
1   F  30.0
2   F  24.0
3   D   2.9
4   ?  25.0